on:
  push:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: build
        run: ./scripts/buildprod.sh

     

