name: ci
on:
  pull_request:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run go tests
        run: go test -cover ./... 

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22'

      - name: Run Format tests
        run: test -z $(go fmt ./...)
        
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Linting tests
        run: test -z $(staticcheck ./...)
